services:
  mlflow:
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
    command: >
      mlflow server
      --backend-store-uri postgresql://admin:admin@postgres:5432/mlflow_db
      --default-artifact-root gs://mlflow-tracking-exp/research
      --host 0.0.0.0
      --port 5000
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mlflow_db
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: